# Generated by Django 5.2.5 on 2025-08-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Email Verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Reset Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_code_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reset Code Created'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Verification Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verification Code Created'),
        ),
    ]
